### ISSUE TITLE
ptc_test_1 ImportError

### ISSUE THREAD

**Issue by Jiangxp16** [PyORBIT-Collaboration/PTC#5]
Two Environment setup: _setupEnevironment.sh_ and _customEnvironment.sh_ were both tried. Both came out with error while running the example ptc_test_1 as below:
      ./START.sh run1.py 1
      Traceback (most recent call last):
        File "run1.py", line 21, in <module>
          from ext.ptc_orbit import PTC_Lattice
        File "/home/PyORBIT/py-orbit/py/ext/ptc_orbit/__init__.py", line 9, in <module>
          from ptc_orbit import PTC_Lattice
        File "/home/PyORBIT/py-orbit/py/ext/ptc_orbit/ptc_orbit.py", line 28, in <module>
          from libptc_orbit import *
      ImportError: /home/PyORBIT/py-orbit/lib/libptc_orbit.so: undefined symbol: _gfortran_stop_numeric
Tried many ways but still failed with this '_gfortran_stop_numeric' error.

**Comment by azukov** [comment]
Can you please elaborate what steps have you completed.

1. What system are you using: OS, version etc?
2. Does pyORBIT standard example work (without PTC)?
3.  Have you compiled PTC without errors?

**Comment by Jiangxp16** [comment]
Thanks for your reply!
Here're the details for the questions you mentioned.
1. I tried in both Ubuntu 20.04 LTS and Centos 8. And I built the project from a pure system in virtual machines (ubuntu in vbox and centos in hyper-v).
2. pyORBIT example works well.
3. I built py-orbit and PTC according to their installation guides, and no errors happened while compiling.

I am really confused if I was the only one who had this error.
Looking forward to your replies. Thank you.

**Comment by azukov** [comment]
The last build was probably done on older Linux distributions (Centos 7).
I will try to build on Centos 8 tomorrow.
Thanks for reporting this!

**Comment by Jiangxp16** [comment]
Thank you! I'll try it with Centos 7 too.

**Comment by Jiangxp16** [comment]
PTC examples run well without errors on Centos 7. It seems to be not compatible with the newest ubuntu and centos 8 in some ways.
I'll close this issue after your test on Centos 8.
Thank you again! @azukov

**Comment by azukov** [comment]
Indeed I can see the issue on Ubuntu 20.04.

I don't see it on Centos8 though. I tried running it in docker with following commands.
First run docker container

```bash
docker run -it centos:centos8 bash
```
Then inside docker:
```bash
yum update
yum group install "Development Tools"
yum install python-devel mpich mpich-devel zlib-devel fftw-devel
yum install python2-devel mpich mpich-devel zlib-devel fftw-devel
git clone https://github.com/PyORBIT-Collaboration/py-orbit.git
cd py-orbit/
. setupEnvironment.sh
make
cd ../
git clone https://github.com/PyORBIT-Collaboration/PTC.git
cd PTC/
make
cd examples/ptc_test_1/
./START.sh run1.py 2
```
Everything worked, I wonder if you installed something else in your VM?

**Comment by Jiangxp16** [comment]
You're right. I tried again within a new centos 8 os, and it worked well.
Honestly now I'm not sure if I installed other development tools before. I'll check it again later.
Thanks for your time testing this problem!
